#include "CharacterAnimTable.h"

#pragma region SUNGJINWOO_ERANK

#pragma endregion

#pragma region SUNGJINWOO_OVERDRIVE
static const CHARACTER_ANIM_BIND_DESC s_SungJinWooOverDrive_Binds[] =
{
		  { CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::IDLE,           CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Idle",          false },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::WALK,           CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Walk",          false },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN,            CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run",           false },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_FAST,       CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run_Fast_2",    false },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_FAST_LEFT,  CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run_FastLeft",  false },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_FAST_RIGHT, CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run_FastRight", false },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::DASH,           CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Dash",          true  },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::BACK_DASH,      CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "BackDash",      true  },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_END,        CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run_End",       true  },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_END_LEFT,   CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run_End_Left",  true  },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_END_RIGHT,  CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Run_End_Right", true  },
		{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::UNDRAW,         CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Undraw_Weapon", true  },

		// 기본 공격
		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::BASIC_ATTACK_01, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "BaseAttack_01", true },
		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::BASIC_ATTACK_02, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "BaseAttack_02", true },
		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::BASIC_ATTACK_03, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "BaseAttack_03", true },
		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::BASIC_ATTACK_01, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DAGGER,  EQUIPPED_WEAPON_ID::NONE, "BaseAttack_01", true },
		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::BASIC_ATTACK_02, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DAGGER,  EQUIPPED_WEAPON_ID::NONE, "BaseAttack_02", true },
		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::BASIC_ATTACK_03, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DAGGER,  EQUIPPED_WEAPON_ID::NONE, "BaseAttack_03", true },

		// GUARD
		{ CHARACTER_STATE::GUARD, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::START, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Guard_Dagger_Start", true  },
		{ CHARACTER_STATE::GUARD, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::LOOP,  WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Guard_Dagger_Loop",  false },
		{ CHARACTER_STATE::GUARD, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::END,   WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Guard_Dagger_End",   true  },
		{ CHARACTER_STATE::GUARD, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::START, WEAPON_TYPE::DAGGER,  EQUIPPED_WEAPON_ID::NONE, "Guard_Dagger_Start", true  },
		{ CHARACTER_STATE::GUARD, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::LOOP,  WEAPON_TYPE::DAGGER,  EQUIPPED_WEAPON_ID::NONE, "Guard_Dagger_Loop",  false },
		{ CHARACTER_STATE::GUARD, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::END,   WEAPON_TYPE::DAGGER,  EQUIPPED_WEAPON_ID::NONE, "Guard_Dagger_End",   true  },

		// Hit reaction / down
		{ CHARACTER_STATE::AIRBORNE, CHARACTER_ACTION::FLOAT_A,        CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Float_A",       true },
		{ CHARACTER_STATE::AIRBORNE, CHARACTER_ACTION::FLOAT_B,        CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Float_B",       true },
		{ CHARACTER_STATE::DOWN,     CHARACTER_ACTION::FLOAT_END,      CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Float_End",     true },
		{ CHARACTER_STATE::DOWN,     CHARACTER_ACTION::DOWN_RECOVERY,  CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Down_Recovery", true },
		{ CHARACTER_STATE::DOWN,     CHARACTER_ACTION::BREAKFALL,      CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DEFAULT, EQUIPPED_WEAPON_ID::NONE, "Breakfall",     true },

		{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::WEAPON_SWAP, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::NONE, "Skill_017", true },

		  // F — SKILL_F : Kasaka 단일 NONE
		  { CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KASAKA_VENOM_FANG, "GS_Skill01_SSR_KasakaVenomFang", true },

			// F — SKILL_F : KnightKiller START / LOOP / END
			{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::START,  WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KNIGHT_KILLER, "GS_Skill01_KnightKiller_Start", true },
			{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::LOOP,  WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KNIGHT_KILLER,  "GS_Skill01_KnightKiller_Loop", true },
			{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::END,  WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KNIGHT_KILLER,  "GS_Skill01_KnightKiller_End", true },

			  // Q — SKILL_Q : A=B 동일 (EQUIPPED_ID=NONE 폴백)
			  { CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_Q, CHARACTER_ACTION_STEP::NONE, WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::NONE, "Skill_03_02", true },

				// E — SKILL_E : Kasaka 단일
				{ CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::NONE,  WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KASAKA_VENOM_FANG,  "Skill_08", true },

				  // E — SKILL_E : KnightKiller START / LOOP / END_01
				  { CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::START,WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KNIGHT_KILLER,"Skill_06_Start", true },
				  { CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::LOOP,WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KNIGHT_KILLER,	"Skill_06_Loop", true },
				  { CHARACTER_STATE::COMBAT, CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::END,	WEAPON_TYPE::DAGGER, EQUIPPED_WEAPON_ID::KNIGHT_KILLER,	"Skill_06_End_01", true },

};

static const CHARACTER_ACTION_POLICY s_SungJinWooOverDrive_Policies[] =
{
	// 기본 이동 — priority 0, 자기 자신 복귀
	  { CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0, false, CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::WALK,            CHARACTER_ACTION_STEP::NONE, 0, false, CHARACTER_ACTION::WALK,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::RUN,             CHARACTER_ACTION_STEP::NONE, 0, false, CHARACTER_ACTION::RUN,             CHARACTER_ACTION_STEP::NONE, 0.15f },

	  { CHARACTER_ACTION::RUN_FAST,        CHARACTER_ACTION_STEP::NONE, 0, false, CHARACTER_ACTION::RUN_FAST,        CHARACTER_ACTION_STEP::NONE, 0.25f },
	  { CHARACTER_ACTION::RUN_FAST_LEFT,   CHARACTER_ACTION_STEP::NONE, 0, false, CHARACTER_ACTION::RUN_FAST_LEFT,   CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::RUN_FAST_RIGHT,  CHARACTER_ACTION_STEP::NONE, 0, false, CHARACTER_ACTION::RUN_FAST_RIGHT,  CHARACTER_ACTION_STEP::NONE, 0.15f },

	  // 회피 — priority 2, 복귀 시 IDLE
	  { CHARACTER_ACTION::DASH,            CHARACTER_ACTION_STEP::NONE, 6, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.03f },
	  { CHARACTER_ACTION::BACK_DASH,       CHARACTER_ACTION_STEP::NONE, 6, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.03f },

	  // 정지 분기 — priority 1 복귀 시 IDLE
	  { CHARACTER_ACTION::RUN_END,         CHARACTER_ACTION_STEP::NONE, 1, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::RUN_END_LEFT,    CHARACTER_ACTION_STEP::NONE, 1, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::RUN_END_RIGHT,   CHARACTER_ACTION_STEP::NONE, 1, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::UNDRAW,          CHARACTER_ACTION_STEP::NONE, 1, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },

	  { CHARACTER_ACTION::BASIC_ATTACK_01, CHARACTER_ACTION_STEP::NONE, 3, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::BASIC_ATTACK_02, CHARACTER_ACTION_STEP::NONE, 3, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },
	  { CHARACTER_ACTION::BASIC_ATTACK_03, CHARACTER_ACTION_STEP::NONE, 3, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.15f },

	  // GUARD — R1 에선 NONE 유지 (R2 에서 START/LOOP/END 로 마이그레이션)
		{ CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::START, 4, false, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::START, 0.08f },
		  { CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::LOOP,  4, false, CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::LOOP,  0.10f },
		  { CHARACTER_ACTION::GUARD, CHARACTER_ACTION_STEP::END,   4, true,  CHARACTER_ACTION::IDLE,  CHARACTER_ACTION_STEP::NONE,  0.10f },

	  { CHARACTER_ACTION::FLOAT_A,         CHARACTER_ACTION_STEP::NONE, 7, true,  CHARACTER_ACTION::FLOAT_END,       CHARACTER_ACTION_STEP::NONE, 0.05f },
	  { CHARACTER_ACTION::FLOAT_B,         CHARACTER_ACTION_STEP::NONE, 7, true,  CHARACTER_ACTION::FLOAT_END,       CHARACTER_ACTION_STEP::NONE, 0.08f },
	  { CHARACTER_ACTION::FLOAT_END,       CHARACTER_ACTION_STEP::NONE, 7, false, CHARACTER_ACTION::FLOAT_END,       CHARACTER_ACTION_STEP::NONE, 0.05f },
	  { CHARACTER_ACTION::DOWN_RECOVERY,   CHARACTER_ACTION_STEP::NONE, 7, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.10f },
	  { CHARACTER_ACTION::BREAKFALL,       CHARACTER_ACTION_STEP::NONE, 7, true,  CHARACTER_ACTION::IDLE,            CHARACTER_ACTION_STEP::NONE, 0.05f },

	  { CHARACTER_ACTION::WEAPON_SWAP, CHARACTER_ACTION_STEP::NONE, 5, true, CHARACTER_ACTION::IDLE, CHARACTER_ACTION_STEP::NONE, 0.05f },

			// F — SKILL_F : Kasaka NONE / KnightKiller START / LOOP / END
			{ CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::NONE, 5, true,  CHARACTER_ACTION::IDLE, CHARACTER_ACTION_STEP::NONE, 0.10f },
			{ CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::START, 5, false,  CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::START, 0.08f },
			{ CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::LOOP, 5, false,  CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::LOOP, 0.10f },
			{ CHARACTER_ACTION::SKILL_F, CHARACTER_ACTION_STEP::END, 5, true,  CHARACTER_ACTION::IDLE, CHARACTER_ACTION_STEP::NONE, 0.10f },

			  // Q — SKILL_Q : 단일 NONE
			  { CHARACTER_ACTION::SKILL_Q, CHARACTER_ACTION_STEP::NONE, 5, true, CHARACTER_ACTION::IDLE, CHARACTER_ACTION_STEP::NONE, 0.10f },

				// E — SKILL_E : Kasaka NONE / KnightKiller START / LOOP / END
				{ CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::NONE, 5, true,  CHARACTER_ACTION::IDLE, CHARACTER_ACTION_STEP::NONE, 0.10f },
				{ CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::START, 5, false, CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::START, 0.08f },
				{ CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::LOOP, 5, false,  CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::LOOP, 0.10f },
				{ CHARACTER_ACTION::SKILL_E, CHARACTER_ACTION_STEP::END, 5, true,  CHARACTER_ACTION::IDLE, CHARACTER_ACTION_STEP::NONE, 0.10f },

};

static const CHARACTER_ANIM_TABLE_DESC s_SungJinWooOverDriveAnimTable =
{
	CHARACTER_TYPE::SUNGJINWOO_OVERDRIVE,
	  TEXT("Prototype_Component_Model_SungJinWoo_OverDrive"),
	  "Translate",

	  s_SungJinWooOverDrive_Binds,
	  static_cast<_uint>(_countof(s_SungJinWooOverDrive_Binds)),

	  s_SungJinWooOverDrive_Policies,
	  static_cast<_uint>(_countof(s_SungJinWooOverDrive_Policies))
};

#pragma endregion
const CHARACTER_ANIM_TABLE_DESC* Client::Find_CharacterAnimTable(CHARACTER_TYPE eAnimSet)
{
	switch (eAnimSet)
	{
	//case CHARACTER_TYPE::SUNGJINWOO_ERANK:
	//	return Get_SungJinWooERankAnimTable();
	case CHARACTER_TYPE::SUNGJINWOO_OVERDRIVE:
		return Get_SungJinWooOverDriveAnimTable();
	default:
		return nullptr;
	}
}

//const CHARACTER_ANIM_TABLE_DESC* Client::Get_SungJinWooERankAnimTable()
//{
//	return &s_SungJinWooERankAnimTable;
//}

const CHARACTER_ANIM_TABLE_DESC* Client::Get_SungJinWooOverDriveAnimTable()
{
	return &s_SungJinWooOverDriveAnimTable;
}
