#include "CharacterAnimTable.h"

static const CHARACTER_ANIM_BIND_DESC s_SungJinWooERankClips[] =
{
	{ CHARACTER_ACTION::IDLE,		CHARACTER_WEAPON_STATE::COMMON,		"Normal_Idle",	false },
	{ CHARACTER_ACTION::WALK,		CHARACTER_WEAPON_STATE::COMMON,		"Walk",			false },
	{ CHARACTER_ACTION::RUN,		CHARACTER_WEAPON_STATE::COMMON,		"Run",			false },

	{ CHARACTER_ACTION::DASH,		CHARACTER_WEAPON_STATE::COMMON,		"Dash",			true },
	{ CHARACTER_ACTION::BACK_DASH,	CHARACTER_WEAPON_STATE::COMMON,		"BackDash",		true },

	{ CHARACTER_ACTION::BASIC_ATTACK_01,	CHARACTER_WEAPON_STATE::UNARMED,	"BaseAttack_01",	true },
	{ CHARACTER_ACTION::BASIC_ATTACK_02,	CHARACTER_WEAPON_STATE::UNARMED,	"BaseAttack_02",	true },
	{ CHARACTER_ACTION::BASIC_ATTACK_03,	CHARACTER_WEAPON_STATE::UNARMED,	"BaseAttack_03",	true },
	{ CHARACTER_ACTION::CORE_ATTACK_01,		CHARACTER_WEAPON_STATE::UNARMED,	"CoreAttack_01",	true },
	{ CHARACTER_ACTION::SKILL_01,			CHARACTER_WEAPON_STATE::UNARMED,	"Skill_01",			true },
	{ CHARACTER_ACTION::SKILL_02,			CHARACTER_WEAPON_STATE::UNARMED,	"Skill_02",			true },
	{ CHARACTER_ACTION::U_SKILL,			CHARACTER_WEAPON_STATE::UNARMED,	"USkill",			true },

	{ CHARACTER_ACTION::BASIC_ATTACK_01,	CHARACTER_WEAPON_STATE::FIGHTER,	"BaseAttack_01_Fighter",	true },
	{ CHARACTER_ACTION::BASIC_ATTACK_02,	CHARACTER_WEAPON_STATE::FIGHTER,	"BaseAttack_02_Fighter",	true },
	{ CHARACTER_ACTION::BASIC_ATTACK_03,	CHARACTER_WEAPON_STATE::FIGHTER,	"BaseAttack_03_Fighter",	true },
	{ CHARACTER_ACTION::CORE_ATTACK_01,		CHARACTER_WEAPON_STATE::FIGHTER,	"CoreAttack_01_Fighter",	true },
	{ CHARACTER_ACTION::SKILL_01,			CHARACTER_WEAPON_STATE::FIGHTER,	"Skill_01_Fighter",			true },
	{ CHARACTER_ACTION::SKILL_02,			CHARACTER_WEAPON_STATE::FIGHTER,	"Skill_02_Fighter",			true },

	{ CHARACTER_ACTION::SKILL_01,			CHARACTER_WEAPON_STATE::ONE_HAND_SWORD,	"Skill_01_Sword",					true },
	{ CHARACTER_ACTION::SKILL_02,			CHARACTER_WEAPON_STATE::ONE_HAND_SWORD,	"GS_ChainSmash_01_OneHandSword",	true },

	{ CHARACTER_ACTION::GUARD_START,	CHARACTER_WEAPON_STATE::UNARMED,	"Guard_Start",	true },
	{ CHARACTER_ACTION::GUARD_LOOP,		CHARACTER_WEAPON_STATE::UNARMED,	"Guard_Loop",	false },
	{ CHARACTER_ACTION::GUARD_END,		CHARACTER_WEAPON_STATE::UNARMED,	"Guard_End",	true },

	{ CHARACTER_ACTION::GUARD_START,	CHARACTER_WEAPON_STATE::FIGHTER,	"Guard_Fighter_Start",	true },
	{ CHARACTER_ACTION::GUARD_LOOP,		CHARACTER_WEAPON_STATE::FIGHTER,	"Guard_Fighter_Loop",	false },
	{ CHARACTER_ACTION::GUARD_END,		CHARACTER_WEAPON_STATE::FIGHTER,	"Guard_Fighter_End",	true },

	{ CHARACTER_ACTION::PARRY_WEAK,		CHARACTER_WEAPON_STATE::UNARMED,	"Parrying_Weak",	true },
	{ CHARACTER_ACTION::PARRY_STRONG,	CHARACTER_WEAPON_STATE::UNARMED,	"Parrying_Strong",	true },

	{ CHARACTER_ACTION::PARRY_WEAK,		CHARACTER_WEAPON_STATE::FIGHTER,	"Parrying_Fighter_Weak",	true },
	{ CHARACTER_ACTION::PARRY_STRONG,	CHARACTER_WEAPON_STATE::FIGHTER,	"Parrying_Fighter_Strong",	true },

	{ CHARACTER_ACTION::PARRY_STRONG,	CHARACTER_WEAPON_STATE::DAGGER,		"Parrying_Dagger_Strong",	true },
	//{ CHARACTER_ACTION::PARRY_UPPER_02,	CHARACTER_WEAPON_STATE::DAGGER,		"Parrying_Dagger_Upper_2",	true },
	//{ CHARACTER_ACTION::PARRY_UPPER_03,	CHARACTER_WEAPON_STATE::DAGGER,		"Parrying_Dagger_Upper_3",	true },

	{ CHARACTER_ACTION::BREAKFALL,	CHARACTER_WEAPON_STATE::COMMON,	"Breakfall",	true },
	{ CHARACTER_ACTION::STUN,		CHARACTER_WEAPON_STATE::COMMON,	"Stun",			false },
};

static const CHARACTER_ACTION_POLICY s_SungJinWooERankPolicies[] =
{
	{ CHARACTER_ACTION::DEATH,				6,	false,	CHARACTER_ACTION::DEATH },
	{ CHARACTER_ACTION::HIT,				4,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::STUN,				2,	false,	CHARACTER_ACTION::STUN },

	{ CHARACTER_ACTION::SKILL_01,			1,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::SKILL_02,			1,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::U_SKILL,			5,	true,	CHARACTER_ACTION::IDLE },

	{ CHARACTER_ACTION::CORE_ATTACK_01,		1,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::BASIC_ATTACK_01,	1,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::BASIC_ATTACK_02,	1,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::BASIC_ATTACK_03,	1,	true,	CHARACTER_ACTION::IDLE },

	{ CHARACTER_ACTION::PARRY_WEAK,			4,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::PARRY_STRONG,		4,	true,	CHARACTER_ACTION::IDLE },
	//{ CHARACTER_ACTION::PARRY_UPPER_02,		550,	true,	CHARACTER_ACTION::IDLE },
	//{ CHARACTER_ACTION::PARRY_UPPER_03,		550,	true,	CHARACTER_ACTION::IDLE },

	{ CHARACTER_ACTION::DASH,				2,	true,	CHARACTER_ACTION::IDLE },
	{ CHARACTER_ACTION::BACK_DASH,			2,	true,	CHARACTER_ACTION::IDLE },

	{ CHARACTER_ACTION::GUARD_START,		3,	true,	CHARACTER_ACTION::GUARD_LOOP },
	{ CHARACTER_ACTION::GUARD_LOOP,			3,	false,	CHARACTER_ACTION::GUARD_LOOP },
	{ CHARACTER_ACTION::GUARD_END,			3,	true,	CHARACTER_ACTION::IDLE },

	{ CHARACTER_ACTION::RUN,				0,		false,	CHARACTER_ACTION::RUN },
	{ CHARACTER_ACTION::WALK,				0,		false,	CHARACTER_ACTION::WALK },
	{ CHARACTER_ACTION::IDLE,				0,		false,	CHARACTER_ACTION::IDLE },
};

static const CHARACTER_ANIM_TABLE_DESC s_SungJinWooERankAnimTable =
{
        CHARACTER_ANIM_SET::SUNGJINWOO_ERANK,
        TEXT("Prototype_Component_Model_SungJinWoo"),
        "Translate",

        s_SungJinWooERankClips,
        static_cast<_uint>(_countof(s_SungJinWooERankClips)),

        s_SungJinWooERankPolicies,
        static_cast<_uint>(_countof(s_SungJinWooERankPolicies))
};

const CHARACTER_ANIM_TABLE_DESC* Client::Find_CharacterAnimTable(CHARACTER_ANIM_SET eAnimSet)
{
	switch (eAnimSet)
	{
	case CHARACTER_ANIM_SET::SUNGJINWOO_ERANK:
		return Get_SungJinWooERankAnimTable();

	default:
		return nullptr;
	}
}

const CHARACTER_ANIM_TABLE_DESC* Client::Get_SungJinWooERankAnimTable()
{
	return &s_SungJinWooERankAnimTable;
}
