#include "CharacterAnimTable.h"

#pragma region SUNGJINWOO_ERANK
//static const CHARACTER_ANIM_BIND_DESC s_SungJinWooERankClips[] =
//{
//	{ CHARACTER_ACTION::IDLE,		CHARACTER_WEAPON_STATE::COMMON,		"Normal_Idle",	false },
//	{ CHARACTER_ACTION::WALK,		CHARACTER_WEAPON_STATE::COMMON,		"Walk",			false },
//	{ CHARACTER_ACTION::RUN,		CHARACTER_WEAPON_STATE::COMMON,		"Run",			false },
//
//	{ CHARACTER_ACTION::DASH,		CHARACTER_WEAPON_STATE::COMMON,		"Dash",			true },
//	{ CHARACTER_ACTION::BACK_DASH,	CHARACTER_WEAPON_STATE::COMMON,		"BackDash",		true },
//
//	{ CHARACTER_ACTION::BASIC_ATTACK_01,	CHARACTER_WEAPON_STATE::UNARMED,	"BaseAttack_01",	true },
//	{ CHARACTER_ACTION::BASIC_ATTACK_02,	CHARACTER_WEAPON_STATE::UNARMED,	"BaseAttack_02",	true },
//	{ CHARACTER_ACTION::BASIC_ATTACK_03,	CHARACTER_WEAPON_STATE::UNARMED,	"BaseAttack_03",	true },
//	{ CHARACTER_ACTION::CORE_ATTACK_01,		CHARACTER_WEAPON_STATE::UNARMED,	"CoreAttack_01",	true },
//	{ CHARACTER_ACTION::SKILL_01,			CHARACTER_WEAPON_STATE::UNARMED,	"Skill_01",			true },
//	{ CHARACTER_ACTION::SKILL_02,			CHARACTER_WEAPON_STATE::UNARMED,	"Skill_02",			true },
//	{ CHARACTER_ACTION::U_SKILL,			CHARACTER_WEAPON_STATE::UNARMED,	"USkill",			true },
//
//	{ CHARACTER_ACTION::BASIC_ATTACK_01,	CHARACTER_WEAPON_STATE::FIGHTER,	"BaseAttack_01_Fighter",	true },
//	{ CHARACTER_ACTION::BASIC_ATTACK_02,	CHARACTER_WEAPON_STATE::FIGHTER,	"BaseAttack_02_Fighter",	true },
//	{ CHARACTER_ACTION::BASIC_ATTACK_03,	CHARACTER_WEAPON_STATE::FIGHTER,	"BaseAttack_03_Fighter",	true },
//	{ CHARACTER_ACTION::CORE_ATTACK_01,		CHARACTER_WEAPON_STATE::FIGHTER,	"CoreAttack_01_Fighter",	true },
//	{ CHARACTER_ACTION::SKILL_01,			CHARACTER_WEAPON_STATE::FIGHTER,	"Skill_01_Fighter",			true },
//	{ CHARACTER_ACTION::SKILL_02,			CHARACTER_WEAPON_STATE::FIGHTER,	"Skill_02_Fighter",			true },
//
//	{ CHARACTER_ACTION::SKILL_01,			CHARACTER_WEAPON_STATE::ONE_HAND_SWORD,	"Skill_01_Sword",					true },
//	{ CHARACTER_ACTION::SKILL_02,			CHARACTER_WEAPON_STATE::ONE_HAND_SWORD,	"GS_ChainSmash_01_OneHandSword",	true },
//
//	{ CHARACTER_ACTION::GUARD_START,	CHARACTER_WEAPON_STATE::UNARMED,	"Guard_Start",	true },
//	{ CHARACTER_ACTION::GUARD_LOOP,		CHARACTER_WEAPON_STATE::UNARMED,	"Guard_Loop",	false },
//	{ CHARACTER_ACTION::GUARD_END,		CHARACTER_WEAPON_STATE::UNARMED,	"Guard_End",	true },
//
//	{ CHARACTER_ACTION::GUARD_START,	CHARACTER_WEAPON_STATE::FIGHTER,	"Guard_Fighter_Start",	true },
//	{ CHARACTER_ACTION::GUARD_LOOP,		CHARACTER_WEAPON_STATE::FIGHTER,	"Guard_Fighter_Loop",	false },
//	{ CHARACTER_ACTION::GUARD_END,		CHARACTER_WEAPON_STATE::FIGHTER,	"Guard_Fighter_End",	true },
//
//	{ CHARACTER_ACTION::PARRY_WEAK,		CHARACTER_WEAPON_STATE::UNARMED,	"Parrying_Weak",	true },
//	{ CHARACTER_ACTION::PARRY_STRONG,	CHARACTER_WEAPON_STATE::UNARMED,	"Parrying_Strong",	true },
//
//	{ CHARACTER_ACTION::PARRY_WEAK,		CHARACTER_WEAPON_STATE::FIGHTER,	"Parrying_Fighter_Weak",	true },
//	{ CHARACTER_ACTION::PARRY_STRONG,	CHARACTER_WEAPON_STATE::FIGHTER,	"Parrying_Fighter_Strong",	true },
//
//	{ CHARACTER_ACTION::PARRY_STRONG,	CHARACTER_WEAPON_STATE::DAGGER,		"Parrying_Dagger_Strong",	true },
//	//{ CHARACTER_ACTION::PARRY_UPPER_02,	CHARACTER_WEAPON_STATE::DAGGER,		"Parrying_Dagger_Upper_2",	true },
//	//{ CHARACTER_ACTION::PARRY_UPPER_03,	CHARACTER_WEAPON_STATE::DAGGER,		"Parrying_Dagger_Upper_3",	true },
//
//	{ CHARACTER_ACTION::BREAKFALL,	CHARACTER_WEAPON_STATE::COMMON,	"Breakfall",	true },
//	{ CHARACTER_ACTION::STUN,		CHARACTER_WEAPON_STATE::COMMON,	"Stun",			false },
//};
//
//static const CHARACTER_ACTION_POLICY s_SungJinWooERankPolicies[] =
//{
//	{ CHARACTER_ACTION::DEATH,				6,	false,	CHARACTER_ACTION::DEATH },
//	{ CHARACTER_ACTION::HIT,				4,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::STUN,				2,	false,	CHARACTER_ACTION::STUN },
//
//	{ CHARACTER_ACTION::SKILL_01,			1,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::SKILL_02,			1,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::U_SKILL,			5,	true,	CHARACTER_ACTION::IDLE },
//
//	{ CHARACTER_ACTION::CORE_ATTACK_01,		1,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::BASIC_ATTACK_01,	1,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::BASIC_ATTACK_02,	1,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::BASIC_ATTACK_03,	1,	true,	CHARACTER_ACTION::IDLE },
//
//	{ CHARACTER_ACTION::PARRY_WEAK,			4,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::PARRY_STRONG,		4,	true,	CHARACTER_ACTION::IDLE },
//	//{ CHARACTER_ACTION::PARRY_UPPER_02,		550,	true,	CHARACTER_ACTION::IDLE },
//	//{ CHARACTER_ACTION::PARRY_UPPER_03,		550,	true,	CHARACTER_ACTION::IDLE },
//
//	{ CHARACTER_ACTION::DASH,				2,	true,	CHARACTER_ACTION::IDLE },
//	{ CHARACTER_ACTION::BACK_DASH,			2,	true,	CHARACTER_ACTION::IDLE },
//
//	{ CHARACTER_ACTION::GUARD_START,		3,	true,	CHARACTER_ACTION::GUARD_LOOP },
//	{ CHARACTER_ACTION::GUARD_LOOP,			3,	false,	CHARACTER_ACTION::GUARD_LOOP },
//	{ CHARACTER_ACTION::GUARD_END,			3,	true,	CHARACTER_ACTION::IDLE },
//
//	{ CHARACTER_ACTION::RUN,				0,		false,	CHARACTER_ACTION::RUN },
//	{ CHARACTER_ACTION::WALK,				0,		false,	CHARACTER_ACTION::WALK },
//	{ CHARACTER_ACTION::IDLE,				0,		false,	CHARACTER_ACTION::IDLE },
//};
//
//static const CHARACTER_ANIM_TABLE_DESC s_SungJinWooERankAnimTable =
//{
//        CHARACTER_ANIM_SET::SUNGJINWOO_ERANK,
//        TEXT("Prototype_Component_Model_SungJinWoo_ERank"),
//        "Translate",
//
//        s_SungJinWooERankClips,
//        static_cast<_uint>(_countof(s_SungJinWooERankClips)),
//
//        s_SungJinWooERankPolicies,
//        static_cast<_uint>(_countof(s_SungJinWooERankPolicies))
//};

#pragma endregion

#pragma region SUNGJINWOO_OVERDRIVE
static const CHARACTER_ANIM_BIND_DESC s_SungJinWooOverDrive_Binds[] =
{
	{CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::IDLE,				WEAPON_TYPE::DEFAULT,	"Idle",				false },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::WALK,				WEAPON_TYPE::DEFAULT,	"Walk",				false },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN,				WEAPON_TYPE::DEFAULT,	"Run",				false },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_FAST,			WEAPON_TYPE::DEFAULT,	"Run_Fast_2",		false },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_FAST_LEFT,     WEAPON_TYPE::DEFAULT,	"Run_FastLeft",		false },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_FAST_RIGHT,    WEAPON_TYPE::DEFAULT,	"Run_FastRight",    false },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::DASH,				WEAPON_TYPE::DEFAULT,	"Dash",				true  },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::BACK_DASH,			WEAPON_TYPE::DEFAULT,	"BackDash",			true  },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_END,			WEAPON_TYPE::DEFAULT,	"Run_End",			true },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_END_LEFT,		WEAPON_TYPE::DEFAULT,	"Run_End_Left",		true  },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::RUN_END_RIGHT,		WEAPON_TYPE::DEFAULT,	"Run_End_Right",	true  },
	{ CHARACTER_STATE::LOCOMOTION, CHARACTER_ACTION::UNDRAW,			WEAPON_TYPE::DEFAULT,	"Undraw_Weapon",	true },
};

static const CHARACTER_ACTION_POLICY s_SungJinWooOverDrive_Policies[] =
{
	// 기본 이동 - priority 0, 자기 보존
	{ CHARACTER_ACTION::IDLE,				0,	false,	CHARACTER_ACTION::IDLE,				0.15f},
	  { CHARACTER_ACTION::WALK,				0,	false,	CHARACTER_ACTION::WALK,				0.15f},
	  { CHARACTER_ACTION::RUN,				0,	false,	CHARACTER_ACTION::RUN,				0.15f},

	  { CHARACTER_ACTION::RUN_FAST,			0,	false,	CHARACTER_ACTION::RUN_FAST,			0.25f},
	  { CHARACTER_ACTION::RUN_FAST_LEFT,    0,	false,	CHARACTER_ACTION::RUN_FAST_LEFT,	0.15f},
	  { CHARACTER_ACTION::RUN_FAST_RIGHT,	0,	false,	CHARACTER_ACTION::RUN_FAST_RIGHT,	0.15f},

	  // 회피 - priority 2, 종료 후  IDLE (입력 있으면 코드에서 RUN_FAST로 가로챔)
	  { CHARACTER_ACTION::DASH,				2,	true,	CHARACTER_ACTION::IDLE,				0.03f},
	  { CHARACTER_ACTION::BACK_DASH,		2,	true,	CHARACTER_ACTION::IDLE,				0.03f},

	  // 정지 분기 - priority 1 종료 후 IDLE (이동 입력 재개 시  RUN으로 가로챔)
		{ CHARACTER_ACTION::RUN_END,		1,	true,	CHARACTER_ACTION::IDLE,				0.15f},
	  { CHARACTER_ACTION::RUN_END_LEFT,		1,	true,	CHARACTER_ACTION::IDLE,				0.15f},
	  { CHARACTER_ACTION::RUN_END_RIGHT,	1,	true,	CHARACTER_ACTION::IDLE,				0.15f},
	 { CHARACTER_ACTION::UNDRAW,			1,	true,	CHARACTER_ACTION::IDLE,				0.15f},
};

static const CHARACTER_ANIM_TABLE_DESC s_SungJinWooOverDriveAnimTable =
{
	CHARACTER_TYPE::SUNGJINWOO_OVERDRIVE,
	  TEXT("Prototype_Component_Model_SungJinWoo_OverDrive"),
	  "Translate",

	  s_SungJinWooOverDrive_Binds,
	  static_cast<_uint>(_countof(s_SungJinWooOverDrive_Binds)),

	  s_SungJinWooOverDrive_Policies,
	  static_cast<_uint>(_countof(s_SungJinWooOverDrive_Policies))
};

#pragma endregion
const CHARACTER_ANIM_TABLE_DESC* Client::Find_CharacterAnimTable(CHARACTER_TYPE eAnimSet)
{
	switch (eAnimSet)
	{
	//case CHARACTER_TYPE::SUNGJINWOO_ERANK:
	//	return Get_SungJinWooERankAnimTable();
	case CHARACTER_TYPE::SUNGJINWOO_OVERDRIVE:
		return Get_SungJinWooOverDriveAnimTable();
	default:
		return nullptr;
	}
}

//const CHARACTER_ANIM_TABLE_DESC* Client::Get_SungJinWooERankAnimTable()
//{
//	return &s_SungJinWooERankAnimTable;
//}

const CHARACTER_ANIM_TABLE_DESC* Client::Get_SungJinWooOverDriveAnimTable()
{
	return &s_SungJinWooOverDriveAnimTable;
}
