#include "MonsterAnimTable.h"

static const MONSTER_ANIM_BIND_DESC s_IgrisBoss_Clips[] =
{
      { MONSTER_ACTION::IDLE, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Battle_Idle", false },

      { MONSTER_ACTION::BASIC_ATTACK_01, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Base_Attack_01", true },
      { MONSTER_ACTION::BASIC_ATTACK_02, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_02", true },

      { MONSTER_ACTION::SKILL_01, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_01", true },
      { MONSTER_ACTION::SKILL_03, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_03", true },
      { MONSTER_ACTION::SKILL_04, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_04", true },
      { MONSTER_ACTION::SKILL_05, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_05", true },
      { MONSTER_ACTION::SKILL_06, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_06", true },
      { MONSTER_ACTION::SKILL_11, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_11", true },
      { MONSTER_ACTION::SKILL_13, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Skill_13", true },

      { MONSTER_ACTION::SKILL_07, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Skill_07_Start", true },
      { MONSTER_ACTION::SKILL_07, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP,  "Skill_07_Loop", false },
      { MONSTER_ACTION::SKILL_07, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::END,   "Skill_07_End", true },

      { MONSTER_ACTION::SKILL_08, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Skill_08_Start", true },
      { MONSTER_ACTION::SKILL_08, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::END,   "Skill_08_End", true },

      { MONSTER_ACTION::SKILL_09, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Skill_09_Start", true },
      { MONSTER_ACTION::SKILL_09, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP,  "Skill_09_Loop", false },
      { MONSTER_ACTION::SKILL_09, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::END,   "Skill_09_End", true },

      { MONSTER_ACTION::SKILL_10, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Skill_10_Start", true },
      { MONSTER_ACTION::SKILL_10, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP,  "Skill_10_Loop", false },
      { MONSTER_ACTION::SKILL_10, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::END,   "Skill_10_End", true },

      { MONSTER_ACTION::SKILL_12, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Skill_12_Start", true },
      { MONSTER_ACTION::SKILL_12, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP,  "Skill_12_Loop", false },
      { MONSTER_ACTION::SKILL_12, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::END,   "Skill_12_End", true },

      { MONSTER_ACTION::SKILL_15, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Skill_15_Start", true },
      { MONSTER_ACTION::SKILL_15, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP,  "Skill_15_Loop", false },
      { MONSTER_ACTION::SKILL_15, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::END,   "Skill_15_End", true },

      { MONSTER_ACTION::CRASH, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::START, "Crash_Start", true },
      { MONSTER_ACTION::CRASH, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP,  "Crash_Loop", false },

      { MONSTER_ACTION::INTRO, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Intro_A", true },

      { MONSTER_ACTION::DEATH, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::NONE, "Dead_A", true },
      { MONSTER_ACTION::DEATH, MONSTER_PHASE::COMMON, MONSTER_ACTION_STEP::LOOP, "Dead_Pose_Loop", false },
};

static const MONSTER_ACTION_POLICY s_IgrisBoss_Policies[] =
{
      { MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0, false, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.15f },

      { MONSTER_ACTION::BASIC_ATTACK_01, MONSTER_ACTION_STEP::NONE, 2, true, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.12f },
      { MONSTER_ACTION::BASIC_ATTACK_02, MONSTER_ACTION_STEP::NONE, 2, true, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.12f },

      { MONSTER_ACTION::SKILL_01, MONSTER_ACTION_STEP::NONE, 3, true, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.15f },
      { MONSTER_ACTION::SKILL_03, MONSTER_ACTION_STEP::NONE, 3, true, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.15f },
      { MONSTER_ACTION::SKILL_05, MONSTER_ACTION_STEP::NONE, 4, true, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.15f },
      { MONSTER_ACTION::SKILL_13, MONSTER_ACTION_STEP::NONE, 4, true, MONSTER_ACTION::IDLE, MONSTER_ACTION_STEP::NONE, 0.f, 0.15f },

      { MONSTER_ACTION::SKILL_09, MONSTER_ACTION_STEP::START, 4, true,  MONSTER_ACTION::SKILL_09, MONSTER_ACTION_STEP::LOOP, 0.f, 0.10f },
      { MONSTER_ACTION::SKILL_09, MONSTER_ACTION_STEP::LOOP,  4, false, MONSTER_ACTION::SKILL_09, MONSTER_ACTION_STEP::LOOP, 0.f, 0.10f },
      { MONSTER_ACTION::SKILL_09, MONSTER_ACTION_STEP::END,   4, true,  MONSTER_ACTION::IDLE,     MONSTER_ACTION_STEP::NONE, 0.f, 0.10f },

      { MONSTER_ACTION::SKILL_12, MONSTER_ACTION_STEP::START, 4, true,  MONSTER_ACTION::SKILL_12, MONSTER_ACTION_STEP::LOOP, 0.f, 0.10f },
      { MONSTER_ACTION::SKILL_12, MONSTER_ACTION_STEP::LOOP,  4, false, MONSTER_ACTION::SKILL_12, MONSTER_ACTION_STEP::LOOP, 0.f, 0.10f },
      { MONSTER_ACTION::SKILL_12, MONSTER_ACTION_STEP::END,   4, true,  MONSTER_ACTION::IDLE,     MONSTER_ACTION_STEP::NONE, 0.f, 0.10f },

      { MONSTER_ACTION::CRASH, MONSTER_ACTION_STEP::START, 5, true,  MONSTER_ACTION::CRASH, MONSTER_ACTION_STEP::LOOP, 0.f, 0.08f },
      { MONSTER_ACTION::CRASH, MONSTER_ACTION_STEP::LOOP,  5, false, MONSTER_ACTION::CRASH, MONSTER_ACTION_STEP::LOOP, 0.f, 0.08f },

      { MONSTER_ACTION::DEATH, MONSTER_ACTION_STEP::NONE, 10, true,  MONSTER_ACTION::DEATH, MONSTER_ACTION_STEP::LOOP, 0.f, 0.05f },
      { MONSTER_ACTION::DEATH, MONSTER_ACTION_STEP::LOOP, 10, false, MONSTER_ACTION::DEATH, MONSTER_ACTION_STEP::LOOP, 0.f, 0.05f },
};

static const MONSTER_ANIM_TABLE_DESC s_IgrisBossAnimTable =
{
      MONSTER_ANIM_SET::IGRIS_BOSS,
      TEXT("Prototype_Component_Model_Monster_Igris_Body"),
      "Translate",

      s_IgrisBoss_Clips,
      static_cast<_uint>(_countof(s_IgrisBoss_Clips)),

      s_IgrisBoss_Policies,
      static_cast<_uint>(_countof(s_IgrisBoss_Policies))
};

const MONSTER_ANIM_TABLE_DESC* Client::Find_MonsterAnimTable(MONSTER_ANIM_SET eAnimSet)
{
    switch (eAnimSet)
    {
    case MONSTER_ANIM_SET::IGRIS_BOSS:
        return Get_IgrisBossAnimTable();

    default:
        return nullptr;
    }
}

const MONSTER_ANIM_TABLE_DESC* Client::Get_IgrisBossAnimTable()
{
    return &s_IgrisBossAnimTable;
}
